title: _theInitialCommit
description: An exploration of the people behind the projects. Each post is an exclusive interview with a member of the open source community.
email: john@theinitialcommit.com
url: "https://theinitialcommit.com"
markdown: kramdown
permalink: pretty
paginate: 10
exclude: ["Gemfile","Gemfile.lock","s3_website.yml"]
gems:
  - jekyll-sitemap
  - jekyll-paginate

sass:
  style: compressed
