title: _theInitialCommit
description: An exploration of the people behind the projects. Each post is an exclusive interview with a member of the open source community.
email: john@theinitialcommit.com
url: "https://theinitialcommit.com"
markdown: kramdown
permalink: pretty
paginate: 10
exclude: ["Gemfile","Gemfile.lock","s3_website.yml","Readme.md"]
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-minimagick

sass:
  style: compressed

twitter_handle: https://twitter.com/_theIntialCommi
og_image: "img/og.png"
twitter_image: "img/twitter.png"

ampdir: amp

mini_magick:
  post:
    source: img/posts
    destination: img/posts/resized
    resize: "1600"
  og:
    source: img/posts
    destination: img/og/posts
    resize: "1200x630"
  twitter:
    source: img/posts
    destination: img/twitter/posts
    resize: "280x150"
